name: Queen_FAITH-MD-v4
services:
  - name: lastcard-md-service
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin
      


