services:
  - type: web
    name: Queen_FAITH-MD-v4
    env: node
    plan: free
    repo: https://github.com/humphreymbise/Queen_FAITH-MD-v4
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false  # Don't include the value here, will be entered manually on Render
      - key: OWNER_NUMBER
        sync: false

